# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "juiceshop" do |juice|
    juice.vm.box = "ubuntu/xenial64"
    juice.vm.network "private_network", ip: "192.168.1.3"
    juice.vm.hostname = "juice.sh"
    juice.vm.provision "file", source: "./default.conf", destination: "/tmp/juice-shop/default.conf"
    juice.vm.provision :shell, path: "bootstrap.sh"
  end

  config.vm.define "waf" do |waf|
    waf.vm.box = "centos/7"
    waf.vm.network "private_network", ip: "192.168.1.2"
  end

end
